# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: store-db
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080